# Generated by Django 4.0.2 on 2022-02-27 14:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cats',
            fields=[
                ('cat_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=20)),
                ('type', models.IntegerField(choices=[(0, 'Rock'), (1, 'Paper'), (2, 'Fire'), (3, 'Water'), (4, 'Sharp')])),
                ('rarity', models.IntegerField(choices=[(1, 'Normal'), (2, 'Rare'), (3, 'Super Rare'), (4, 'Exotic'), (5, 'Legendary'), (6, 'Cat God')])),
            ],
        ),
    ]
