# Generated by Django 4.0.2 on 2022-02-27 16:35

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('backend', '0002_cats'),
    ]

    operations = [
        migrations.CreateModel(
            name='Wildcat',
            fields=[
                ('wildcat_id', models.AutoField(primary_key=True, serialize=False)),
                ('latitude', models.DecimalField(decimal_places=16, max_digits=22)),
                ('longitude', models.DecimalField(decimal_places=16, max_digits=22)),
                ('start_health', models.IntegerField(default=65)),
                ('cat_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='backend.cats')),
            ],
        ),
        migrations.CreateModel(
            name='Catdex',
            fields=[
                ('catdex_id', models.AutoField(primary_key=True, serialize=False)),
                ('level', models.FloatField(default=1)),
                ('health', models.IntegerField()),
                ('cat_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='backend.cats')),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
