# Generated by Django 4.0.1 on 2022-03-01 13:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0003_wildcat_catdex'),
    ]

    operations = [
        migrations.AlterField(
            model_name='wildcat',
            name='start_health',
            field=models.IntegerField(default=54),
        ),
    ]
