# Generated by Django 4.0.2 on 2022-03-01 14:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0003_wildcat_catdex'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cats',
            name='name',
            field=models.CharField(max_length=20, unique=True),
        ),
        migrations.AlterField(
            model_name='wildcat',
            name='start_health',
            field=models.IntegerField(default=83),
        ),
    ]
