# Generated by Django 4.0.2 on 2022-03-01 16:43

import backend.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0006_alter_wildcat_start_health'),
    ]

    operations = [
        migrations.AlterField(
            model_name='wildcat',
            name='start_health',
            field=models.IntegerField(default=backend.models.rand_val),
        ),
    ]
